"""Learned planar object-control graph with shared rigid local deformation.

Controls are geometry samples, NOT recovered bones. Visibility can hide/reveal
saved appearance, but this model cannot invent previously unseen surfaces.
"""
import torch
from torch import nn
import torch.nn.functional as F


def rotate(points,angle):
    c,s=angle.cos(),angle.sin()
    return torch.stack((c*points[...,0]-s*points[...,1],s*points[...,0]+c*points[...,1]),-1)


def bind_points(points,reference,k=4,mask=None):
    if k<1 or points.ndim!=2 or points.shape[-1]!=2 or reference.ndim!=2 or reference.shape[-1]!=2 or len(reference)==0:
        raise ValueError('Nonempty reference controls, 2D points and positive k required')
    distance,index=torch.cdist(points[None],reference[None])[0].topk(min(k,len(reference)),largest=False)
    width=distance[:,-1:].clamp_min(.005)
    weight=torch.softmax(-4*(distance/width).square(),-1)
    if mask is not None:
        height,width_px=mask.shape
        t=torch.linspace(0,1,9,device=points.device)
        path=points[:,None,None]*(1-t[None,None,:,None])+reference[index][:,:,None]*t[None,None,:,None]
        grid=path*path.new_tensor([2*height/width_px,2])-1
        inside=F.grid_sample(mask[None,None].to(points),grid.reshape(1,1,-1,2),align_corners=False,padding_mode='zeros').reshape(len(points),index.shape[1],9).amin(-1)>.5
        restricted=weight*inside; fallback=F.one_hot(torch.zeros(len(points),dtype=torch.long,device=points.device),index.shape[1]).to(weight)
        weight=torch.where(restricted.sum(1,keepdim=True)>0,restricted/restricted.sum(1,keepdim=True).clamp_min(1e-8),fallback)
    return index,weight


def deform_points(points,reference,position,angle_delta,visibility,index,weight):
    """Shared SE(2) control transforms; colour is never generated by this function."""
    if not torch.isfinite(visibility).all() or ((visibility<0)|(visibility>1)).any(): raise ValueError('Visibility must be finite in [0,1]')
    if not torch.isfinite(weight).all() or (weight<0).any() or not torch.allclose(weight.sum(1),torch.ones(len(points),device=weight.device),atol=1e-5):
        raise ValueError('Binding weights must be finite, nonnegative and sum to one')
    local=points[:,None,:2]-reference[index]
    transformed=rotate(local,angle_delta[index])+position[index]
    output=points.clone(); output[:,:2]=(weight[...,None]*transformed).sum(1)
    c=(weight*angle_delta[index].cos()).sum(1); s=(weight*angle_delta[index].sin()).sum(1)
    valid=c.square()+s.square()>1e-10
    averaged=torch.atan2(torch.where(valid,s,torch.zeros_like(s)),torch.where(valid,c,torch.ones_like(c)))
    strongest=angle_delta[index.gather(1,weight.argmax(1,keepdim=True))[:,0]]
    direction=torch.where(valid,averaged,strongest); output[:,4:6]=rotate(points[:,4:6],direction)
    output[:,9]=points[:,9]*(weight*visibility[index]).sum(1)
    return output


class AnimalControlGraph(nn.Module):
    def __init__(self,hidden=64):
        super().__init__(); self.hidden=hidden
        self.encoder=nn.Sequential(nn.Linear(15,hidden),nn.SiLU(),nn.Linear(hidden,hidden),nn.Tanh())
        self.message=nn.Sequential(nn.Linear(hidden+6,hidden),nn.SiLU(),nn.Linear(hidden,hidden),nn.Tanh())
        self.gru=nn.GRUCell(15+hidden,hidden)
        self.head=nn.Sequential(nn.Linear(hidden,hidden),nn.SiLU(),nn.Linear(hidden,6))
        nn.init.zeros_(self.head[-1].weight); nn.init.zeros_(self.head[-1].bias)
        with torch.no_grad(): self.head[-1].bias[3:5]=4

    def features(self,state):
        return torch.cat(((state['position']-state['origin'])/state['scale'],state['velocity']/state['scale']*10,
                          state['acceleration']/state['scale']*10,
                          state['angle'].sin()[...,None],state['angle'].cos()[...,None],state['angular_velocity'][...,None],
                          state['visibility'][...,None],state['colour'],(state['reference']-state['origin'])/state['scale']),-1)

    def initialize(self,position,angle,visibility,colour,adjacency):
        if position.ndim!=4 or position.shape[1]!=3 or position.shape[-1]!=2: raise ValueError('Three B,3,K,2 observed positions required')
        b,_,n,_=position.shape
        for value,shape in [(angle,(b,3,n)),(visibility,(b,3,n)),(colour,(b,n,3)),(adjacency,(b,n,n))]:
            if tuple(value.shape)!=shape: raise ValueError('Mismatched graph input shapes; exactly three observations required')
        ref=position[:,2]; origin=ref.mean(1,keepdim=True)
        scale=(ref.amax(1,keepdim=True)-ref.amin(1,keepdim=True)).amax(-1,keepdim=True).clamp_min(.05)
        velocity=position[:,2]-position[:,1]
        state=dict(position=ref.clone(),reference=ref.clone(),reference_angle=angle[:,2].clone(),angle=angle[:,2].clone(),
                   velocity=velocity,acceleration=velocity-(position[:,1]-position[:,0]),
                   angular_velocity=angle[:,2]-angle[:,1],visibility=visibility[:,2].clone(),
                   colour=colour.clone(),adjacency=adjacency.clone(),origin=origin,scale=scale)
        state['memory']=self.encoder(self.features(state)); return state

    def step(self,state,reset_memory=False):
        p,v,a,h=(state[k] for k in ['position','velocity','angle','memory'])
        if reset_memory: h=torch.zeros_like(h)
        batch,n,_=p.shape
        relp=(p[:,None]-p[:,:,None])/state['scale'][:,None]
        relv=(v[:,None]-v[:,:,None])/state['scale'][:,None]*10
        da=a[:,None]-a[:,:,None]
        message=self.message(torch.cat((h[:,None].expand(-1,n,-1,-1),relp,relv,da.sin()[...,None],da.cos()[...,None]),-1))
        message=(message*state['adjacency'][...,None]).sum(2)
        memory=self.gru(torch.cat((self.features(state),message),-1).reshape(batch*n,-1),h.reshape(batch*n,-1)).reshape(batch,n,-1)
        action=self.head(memory)
        velocity=action[...,3:4].sigmoid()*v+.03*state['scale']*action[...,:2].tanh()
        angular=action[...,4].sigmoid()*state['angular_velocity']+.15*action[...,2].tanh()
        visibility=torch.sigmoid(torch.logit(state['visibility'].clamp(.01,.99))+.5*action[...,5])
        return dict(state,position=p+velocity,velocity=velocity,acceleration=velocity-v,
                    angle=a+angular,angular_velocity=angular,visibility=visibility,memory=memory)
