import { useCallback, useEffect, useState } from 'react'
import './gaussian-workspace.css'
type Row = Record<string, unknown>
type State = {parts?: Row[]; agents?: Row[]; jobs?: Row[]; media?: Row[]; credentials?: Row; remote?: Row; limitations?: string[]}
type Bridge = {request: (path: string, body?: Row) => Promise<unknown>}
const text = (v: unknown, fallback='Not reported') => typeof v === 'string' || typeof v === 'number' ? String(v) : fallback
const rows = (v: unknown): Row[] => Array.isArray(v) ? v.filter(x => x && typeof x === 'object') : []
function api() { const b = (window as unknown as {gaussianStudio?: Bridge}).gaussianStudio; if (!b) throw new Error('Desktop connection unavailable. Open the Electron app.'); return b }
function mediaURL(value: unknown) { if(typeof value !== 'string') return undefined; try {const u=new URL(value); return u.protocol==='gaussian-media:' && u.hostname==='artifact' ? u.href : undefined} catch {return undefined} }

export default function GaussianWorkspace({compact=false}: {compact?: boolean}) {
  const [state,setState]=useState<State|null>(null), [error,setError]=useState(''), [notice,setNotice]=useState(''), [busy,setBusy]=useState(false)
  const [key,setKey]=useState(''), [provider,setProvider]=useState('gemini'), [podId,setPodId]=useState(''), [baseUrl,setBaseUrl]=useState('')
  const refresh=useCallback(async()=>{try{const result=await api().request('/api/state'); if(!result||typeof result!=='object')throw new Error('Invalid backend response');setState(result as State);setError('')}catch(e){setError(e instanceof Error?e.message:'Backend unavailable')}},[])
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>{if(!document.hidden)void refresh()},5000);return()=>window.clearInterval(timer)},[refresh])
  const action=async(path:string,body:Row,message:string)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await api().request(path,body);setNotice(message);await refresh()}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
  const activePod=podId.trim()||text(state?.remote?.podId,'')
  return <main className={`gaussian-workspace ${compact?'is-compact':''}`}>
    <header><div><small>Persistent scene workspace</small><h1>Gaussian part agents</h1><p>Real jobs, explicit ownership, independent quality review.</p></div><button disabled={busy} onClick={()=>void refresh()}>Refresh status</button></header>
    {error&&<p className="gw-error" role="alert">{error}</p>}{notice&&<p className="gw-notice" role="status">{notice}</p>}
    <div className="gw-grid">
      <section className="gw-wide"><h2>Part ownership</h2><p>Unverified bindings block edits. No Gaussian IDs or temporal correspondence are guessed.</p><div className="gw-parts">
        {rows(state?.parts).map((p,i)=><article key={text(p.id,String(i))}><strong>{text(p.label??p.id)}</strong><span className="gw-badge">{p.protected===true?'Protected':p.bindingVerified===true?'Binding verified':'Unbound · blocked'}</span><dl><dt>Agent</dt><dd>{text(p.agentId,'Unassigned')}</dd><dt>Gaussian IDs</dt><dd>{text(p.gaussianCount,'Not bound')}</dd><dt>Identity scope</dt><dd>{text(p.identityScope,'Not verified')}</dd></dl></article>)}
        {!rows(state?.parts).length&&<p>No ownership manifest reported.</p>}</div></section>
      <section><h2>Generate reference</h2><p>Detailed whole apple, slices with pale flesh and red edges, thin red peel, and mouth-held bite reference.</p><button className="gw-primary" disabled={busy||!state} onClick={()=>void action('/api/jobs',{kind:'gemini_reference'},'Reference job submitted. Track its real status below.')}>Generate apple-parts reference</button><p className="gw-small">Uses Gemini API credits. An image reference is not generated 3D geometry or an edited video.</p></section>
      <section><h2>Provider credentials</h2><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="gemini">Gemini</option><option value="runpod">RunPod</option></select></label><label>API key<input type="password" autoComplete="off" spellCheck={false} value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste key for secure local storage" /></label><button disabled={busy||!key.trim()} onClick={()=>{const value=key.trim();setKey('');void action('/api/credentials',{provider,key:value},'Credential submitted. Check provider status.')}}>Save credential</button>{Object.entries(state?.credentials||{}).map(([name,value])=><p key={name}>{name}: {value&&typeof value==='object'?((value as Row).configured===true?'Configured':'Not configured'):text(value)}</p>)}<p className="gw-small">No browser storage, key read-back, or key in agent traces.</p></section>
      <section><h2>Remote processing</h2><p>Worker: {text(state?.remote?.status,'Not connected')} · rate: {text(state?.remote?.rate,'Unknown')}</p><label>Existing pod ID<input value={podId} onChange={e=>setPodId(e.target.value)} placeholder={text(state?.remote?.podId,'Pod ID')} /></label><label>Worker URL<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://…proxy.runpod.net" /></label><div className="gw-actions"><button disabled={busy||!activePod||!baseUrl.trim()} onClick={()=>void action('/api/remote/connect',{podId:activePod,baseUrl:baseUrl.trim()},'Remote connection checked.')}>Connect worker</button><button disabled={busy||!activePod} onClick={()=>void action('/api/jobs',{kind:'remote_preflight'},'Remote preflight submitted; no GPU launch authorized.')}>Check remote GPU</button><button className="gw-stop" disabled={busy||!activePod} onClick={()=>{if(window.confirm(`Stop pod ${activePod}? Running work will be interrupted.`))void action('/api/remote/stop',{podId:activePod},'Stop requested. Verify status before assuming billing stopped.')}}>Stop pod</button></div><p className="gw-small">Checks do not start a pod or buy credits. Video generation remains blocked until a validated worker and part bindings are deployed.</p></section>
      <section><h2>Actual agent activity</h2>{rows(state?.agents).map((a,i)=><article key={text(a.id,String(i))}><strong>{text(a.name??a.id)}</strong><span>{text(a.status)}</span><p>{Array.isArray(a.partIds)?a.partIds.map(v=>text(v)).join(', '):'No assigned parts'}</p></article>)}{!rows(state?.agents).length&&<p>No agent activity reported.</p>}</section>
      <section className="gw-wide"><h2>Jobs, costs & quality</h2>{rows(state?.jobs).map((j,i)=><article key={text(j.id,String(i))}><strong>{text(j.kind??j.id)}</strong><span>{text(j.status)} · {text(j.stage)}</span>{!!j.error&&<p className="gw-error">{text(j.error)}</p>}<p>Cost: {typeof j.cost_usd==='number'?`$${j.cost_usd.toFixed(4)}`:'Not measured'} · Review: {text(j.review,'Not reviewed')}</p></article>)}{!rows(state?.jobs).length&&<p>No jobs reported. Completion is not visual acceptance.</p>}</section>
      <section className="gw-wide"><h2>Actual artifacts</h2><div className="gw-media">{rows(state?.media).map((m,i)=>{const url=mediaURL(m.url);return <figure key={text(m.id,String(i))}>{url?(m.kind==='video'?<video src={url} controls preload="metadata"/>:<img src={url} alt={text(m.title,'Generated reference')} loading="lazy"/>):<p>No trusted artifact URL.</p>}<figcaption>{text(m.title)} · {text(m.review,'Not reviewed')}</figcaption></figure>})}</div>{!rows(state?.media).length&&<p>No media artifact reported.</p>}</section>
    </div>{!!state?.limitations?.length&&<section><h2>Known limitations</h2><ul>{state.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></section>}
  </main>
}
