// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.u64().name("project_id"),
  agentId: __t.string().name("agent_id"),
  agentName: __t.string().name("agent_name"),
  changedBy: __t.identity().name("changed_by"),
  changedAt: __t.u64().name("changed_at"),
  field: __t.string(),
  oldValue: __t.string().name("old_value"),
  newValue: __t.string().name("new_value"),
});
