// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.u64().name("project_id"),
  agentId: __t.string().name("agent_id"),
  agentName: __t.string().name("agent_name"),
  executionOrder: __t.u32().name("execution_order"),
  startedAt: __t.u64().name("started_at"),
  endedAt: __t.u64().name("ended_at"),
  runtimeMs: __t.u64().name("runtime_ms"),
  status: __t.string(),
  startedBy: __t.identity().name("started_by"),
});
