// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentChange = __t.object("AgentChange", {
  id: __t.u64(),
  projectId: __t.u64(),
  agentId: __t.string(),
  agentName: __t.string(),
  changedBy: __t.identity(),
  changedAt: __t.u64(),
  field: __t.string(),
  oldValue: __t.string(),
  newValue: __t.string(),
});
export type AgentChange = __Infer<typeof AgentChange>;

export const AgentRun = __t.object("AgentRun", {
  id: __t.u64(),
  projectId: __t.u64(),
  agentId: __t.string(),
  agentName: __t.string(),
  executionOrder: __t.u32(),
  startedAt: __t.u64(),
  endedAt: __t.u64(),
  runtimeMs: __t.u64(),
  status: __t.string(),
  startedBy: __t.identity(),
});
export type AgentRun = __Infer<typeof AgentRun>;

export const AppConfig = __t.object("AppConfig", {
  name: __t.string(),
  value: __t.string(),
});
export type AppConfig = __Infer<typeof AppConfig>;

export const Collaborator = __t.object("Collaborator", {
  identity: __t.identity(),
  nickname: __t.string(),
  color: __t.string(),
  online: __t.bool(),
  lastSeen: __t.u64(),
});
export type Collaborator = __Infer<typeof Collaborator>;

export const Credential = __t.object("Credential", {
  email: __t.string(),
  salt: __t.string(),
  passwordHash: __t.string(),
});
export type Credential = __Infer<typeof Credential>;

export const EmailCode = __t.object("EmailCode", {
  email: __t.string(),
  purpose: __t.string(),
  code: __t.string(),
  expiresAt: __t.u64(),
  attempts: __t.u32(),
  lastSentAt: __t.u64(),
  requestedBy: __t.identity(),
  verified: __t.bool(),
});
export type EmailCode = __Infer<typeof EmailCode>;

export const Project = __t.object("Project", {
  id: __t.u64(),
  name: __t.string(),
  prompt: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.u64(),
});
export type Project = __Infer<typeof Project>;

export const Session = __t.object("Session", {
  identity: __t.identity(),
  email: __t.string(),
});
export type Session = __Infer<typeof Session>;

export const StudioUser = __t.object("StudioUser", {
  email: __t.string(),
  registeredAt: __t.u64(),
  lastLoginAt: __t.u64(),
});
export type StudioUser = __Infer<typeof StudioUser>;

