// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateWorkspaceReducer from "../create_workspace_reducer";
import EditPartReducer from "../edit_part_reducer";
import RecordTimingReducer from "../record_timing_reducer";
import SetMemberReducer from "../set_member_reducer";

export type CreateWorkspaceParams = __Infer<typeof CreateWorkspaceReducer>;
export type EditPartParams = __Infer<typeof EditPartReducer>;
export type RecordTimingParams = __Infer<typeof RecordTimingReducer>;
export type SetMemberParams = __Infer<typeof SetMemberReducer>;

