// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as RequestCodeProcedure from "../request_code_procedure";
import * as VerifyCodeProcedure from "../verify_code_procedure";

export type RequestCodeArgs = __Infer<typeof RequestCodeProcedure.params>;
export type RequestCodeResult = __Infer<typeof RequestCodeProcedure.returnType>;
export type VerifyCodeArgs = __Infer<typeof VerifyCodeProcedure.params>;
export type VerifyCodeResult = __Infer<typeof VerifyCodeProcedure.returnType>;

