// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateProjectReducer from "../create_project_reducer";
import FinishAgentRunReducer from "../finish_agent_run_reducer";
import LogAgentChangeReducer from "../log_agent_change_reducer";
import ResetPasswordReducer from "../reset_password_reducer";
import SetNicknameReducer from "../set_nickname_reducer";
import SetOnlineReducer from "../set_online_reducer";
import SignInReducer from "../sign_in_reducer";
import SignOutReducer from "../sign_out_reducer";
import SignUpReducer from "../sign_up_reducer";
import StartAgentRunReducer from "../start_agent_run_reducer";

export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type FinishAgentRunParams = __Infer<typeof FinishAgentRunReducer>;
export type LogAgentChangeParams = __Infer<typeof LogAgentChangeReducer>;
export type ResetPasswordParams = __Infer<typeof ResetPasswordReducer>;
export type SetNicknameParams = __Infer<typeof SetNicknameReducer>;
export type SetOnlineParams = __Infer<typeof SetOnlineReducer>;
export type SignInParams = __Infer<typeof SignInReducer>;
export type SignOutParams = __Infer<typeof SignOutReducer>;
export type SignUpParams = __Infer<typeof SignUpReducer>;
export type StartAgentRunParams = __Infer<typeof StartAgentRunReducer>;

