// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  projectId: __t.string().name("project_id"),
  agentId: __t.string().name("agent_id"),
  partId: __t.string().name("part_id"),
  field: __t.string(),
  value: __t.string(),
  revision: __t.u64(),
  updatedAt: __t.u64().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
});
