// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.string().name("project_id"),
  agentId: __t.string().name("agent_id"),
  partId: __t.string().name("part_id"),
  field: __t.string(),
  oldValue: __t.string().name("old_value"),
  newValue: __t.string().name("new_value"),
  revision: __t.u64(),
  editedAt: __t.u64().name("edited_at"),
  editedBy: __t.identity().name("edited_by"),
  operationId: __t.string().name("operation_id"),
});
