// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  projectId: __t.string().name("project_id"),
  jobId: __t.string().name("job_id"),
  agentId: __t.string().name("agent_id"),
  partId: __t.string().name("part_id"),
  sourceStatus: __t.string().name("source_status"),
  sourceQueuedAt: __t.string().name("source_queued_at"),
  sourceStartedAt: __t.string().name("source_started_at"),
  sourceFinishedAt: __t.string().name("source_finished_at"),
  sourceRuntimeMs: __t.u64().name("source_runtime_ms"),
  sourceHasRuntime: __t.bool().name("source_has_runtime"),
  sourceSequence: __t.u32().name("source_sequence"),
  observedAt: __t.u64().name("observed_at"),
  reportedBy: __t.identity().name("reported_by"),
});
