// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  projectId: __t.string(),
  jobId: __t.string(),
  agentId: __t.string(),
  partId: __t.string(),
  status: __t.string(),
  queuedAt: __t.string(),
  startedAt: __t.string(),
  finishedAt: __t.string(),
  runtimeMs: __t.u64(),
  hasRuntime: __t.bool(),
  sequence: __t.u32(),
};
