// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentTiming = __t.object("AgentTiming", {
  key: __t.string(),
  projectId: __t.string(),
  jobId: __t.string(),
  agentId: __t.string(),
  partId: __t.string(),
  sourceStatus: __t.string(),
  sourceQueuedAt: __t.string(),
  sourceStartedAt: __t.string(),
  sourceFinishedAt: __t.string(),
  sourceRuntimeMs: __t.u64(),
  sourceHasRuntime: __t.bool(),
  sourceSequence: __t.u32(),
  observedAt: __t.u64(),
  reportedBy: __t.identity(),
});
export type AgentTiming = __Infer<typeof AgentTiming>;

export const MyActivity = __t.object("MyActivity", {});
export type MyActivity = __Infer<typeof MyActivity>;

export const MyDrafts = __t.object("MyDrafts", {});
export type MyDrafts = __Infer<typeof MyDrafts>;

export const MyEdits = __t.object("MyEdits", {});
export type MyEdits = __Infer<typeof MyEdits>;

export const MyMembers = __t.object("MyMembers", {});
export type MyMembers = __Infer<typeof MyMembers>;

export const MyProjects = __t.object("MyProjects", {});
export type MyProjects = __Infer<typeof MyProjects>;

export const MyTimings = __t.object("MyTimings", {});
export type MyTimings = __Infer<typeof MyTimings>;

export const PartDraft = __t.object("PartDraft", {
  key: __t.string(),
  projectId: __t.string(),
  agentId: __t.string(),
  partId: __t.string(),
  field: __t.string(),
  value: __t.string(),
  revision: __t.u64(),
  updatedAt: __t.u64(),
  updatedBy: __t.identity(),
});
export type PartDraft = __Infer<typeof PartDraft>;

export const PartEdit = __t.object("PartEdit", {
  id: __t.u64(),
  projectId: __t.string(),
  agentId: __t.string(),
  partId: __t.string(),
  field: __t.string(),
  oldValue: __t.string(),
  newValue: __t.string(),
  revision: __t.u64(),
  editedAt: __t.u64(),
  editedBy: __t.identity(),
  operationId: __t.string(),
});
export type PartEdit = __Infer<typeof PartEdit>;

export const WorkspaceActivity = __t.object("WorkspaceActivity", {
  id: __t.u64(),
  projectId: __t.string(),
  kind: __t.string(),
  target: __t.string(),
  detail: __t.string(),
  at: __t.u64(),
  actor: __t.identity(),
});
export type WorkspaceActivity = __Infer<typeof WorkspaceActivity>;

export const WorkspaceMember = __t.object("WorkspaceMember", {
  key: __t.string(),
  projectId: __t.string(),
  identity: __t.identity(),
  role: __t.string(),
  displayName: __t.string(),
  joinedAt: __t.u64(),
});
export type WorkspaceMember = __Infer<typeof WorkspaceMember>;

export const WorkspaceProject = __t.object("WorkspaceProject", {
  id: __t.string(),
  title: __t.string(),
  owner: __t.identity(),
  createdAt: __t.u64(),
});
export type WorkspaceProject = __Infer<typeof WorkspaceProject>;

